#!/usr/bin/env node
/**
 * Builds the FLEX_DEMO renderer as a browser bundle (iOS PWA).
 *
 * Output: apps/ledger-live-desktop/dist-web/
 *   - app.html  (generated by rspack from web/app.html + injected bundle)
 *   - renderer.bundle.js + assets
 *   - index.html, manifest.webmanifest, icons/, sw.js (copied from web/)
 *
 * Usage:
 *   node --require ts-node/register ./tools/build-web.js
 */

const fs = require("fs");
const path = require("path");

process.env.NODE_ENV = "production";
process.env.FLEX_DEMO = "true";
process.env.FLEX_MODE = process.env.FLEX_MODE || "client";

const { rspack } = require("@rspack/core");

const root = path.resolve(__dirname, "..");
const { createWebConfig } = require("./rspack/rspack.web");

const DIST = path.join(root, "dist-web");

function copyStatic() {
  for (const entry of [
    "index.html",
    "manifest.webmanifest",
    "sw.js",
    "icons/icon-180.png",
    "icons/icon-192.png",
    "icons/icon-512.png",
    "icons/apple-touch-icon-180x180.png",
    "icons/apple-touch-icon-152x152.png",
  ]) {
    const from = path.join(root, "web", entry);
    const to = path.join(DIST, entry);
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
    console.log(`[web-build] copied ${entry}`);
  }
}

async function main() {
  fs.rmSync(DIST, { recursive: true, force: true });
  fs.mkdirSync(DIST, { recursive: true });

  const config = createWebConfig("production");
  const stats = await new Promise((resolve, reject) => {
    rspack(config, (err, s) => (err ? reject(err) : resolve(s)));
  });

  const info = stats.toJson({ all: false, errors: true, warnings: true });
  if (stats.hasErrors()) {
    for (const e of info.errors || []) {
      const msg = typeof e.message === "string" ? e.message : String(e.message || e);
      console.error("  ❌", msg.slice(0, 1000));
    }
    process.exitCode = 1;
    return;
  }
  for (const w of info.warnings || []) {
    const msg = typeof w.message === "string" ? w.message : String(w.message || w);
    console.warn("  ⚠️", msg.slice(0, 500));
  }

  const assets = stats.toJson({ assets: true }).assets || [];
  const mainAsset = assets.find(a => a.name === "renderer.bundle.js");
  if (mainAsset) {
    console.log(`✅ renderer.bundle.js: ${(mainAsset.size / 1024 / 1024).toFixed(2)} MB`);
  }

  copyStatic();
  console.log("\n🎉 Web build complete →", DIST);
}

main().catch(err => {
  console.error("Web build failed:", err);
  process.exit(1);
});
